### ISSUE TITLE
Adding slides and video to my presentation

### ISSUE THREAD

**Issue by lauracion** [agu-openscience-innovations/jupyterbook-2023#9]
Hi,

I'd like to edit [this file](https://github.com/agu-openscience-innovations/jupyterbook-2023/blob/main/speaker_content/02-panel-discussion/03-acion.md) to add this text:

`[The slides for this presentation are available by clicking on this link](https://doi.org/10.5281/zenodo.10264925)

[The pre-recorded video for this presentation, captioned to Spanish and English, is available by clicking on this link](https://youtu.be/cxaV5gtKCjQ?si=ebxRZn4Xp6Tc-ign)`

At the moment, I can only do it through the GitHub interphase on my browser (i.e., I don't have access to a Python environment to follow item 3 in [this guideline](https://github.com/agu-openscience-innovations/jupyterbook-2023/blob/35611fef3f75fee931cbb3b5a5538895621ef41b/contributing.md)).

Please advice.

Thank you! 🙏

**Comment by lsterzinger** [comment]
Hi Laura,

You're welcome to add the text and links to the site via the browser interface. The step to compile the notebook with Python is only needed to view your page locally to confirm it's working before pushing your changes publicly - it's totally optional.

I'm also happy to add it myself if you're unsure how to proceed, just let me know!

**Comment by lauracion** [comment]
Thank you, Lucas! PR with the changes sent!
